#
#  generate_rust_constants.py
#  wake-word-detector/spoken-word-detection-model
#
#  Created by Joel Lopes Da Silva on 2/14/26.
#  Copyright © 2026 Joel Lopes Da Silva. All rights reserved.
#

import numpy as np
import tensorflow as tf

hann = tf.signal.hann_window(512, periodic=True).numpy()

# The parameters must match those in `data_loader.py` exactly.
mel_matrix = tf.signal.linear_to_mel_weight_matrix(
    num_mel_bins=40,
    num_spectrogram_bins=257,    # FFT_length / 2 + 1
    sample_rate=16000,
    lower_edge_hertz=80.0,
    upper_edge_hertz=7600.0,
).numpy()

# Analyze sparsity: for each mel bin (column),
# find the range of non-zero FFT bins.
number_of_frequency_bins, number_of_mel_bins = mel_matrix.shape
mel_bin_starts = []
mel_bin_lengths = []
all_weights = []

for mel_bin_index in range(number_of_mel_bins):
    column = mel_matrix[:, mel_bin_index]
    non_zero_indices = np.nonzero(column)[0]
    if len(non_zero_indices) == 0:
        mel_bin_starts.append(0)
        mel_bin_lengths.append(0)
    else:
        start = int(non_zero_indices[0])
        end = int(non_zero_indices[-1]) + 1
        mel_bin_starts.append(start)
        mel_bin_lengths.append(end - start)
        all_weights.extend(column[start:end].tolist())

# Compute offsets into the packed weights array.
mel_bin_offsets = []
offset = 0
for length in mel_bin_lengths:
    mel_bin_offsets.append(offset)
    offset += length

total_weights = len(all_weights)
print(f"Sparse mel filterbank: {total_weights} non-zero weights out of {number_of_frequency_bins * number_of_mel_bins} total ({100 * total_weights / (number_of_frequency_bins * number_of_mel_bins):.1f}%)")

with open("../src/audio/mel_constants.rs", "w") as file:
    file.write("/*\n")
    file.write(" *  audio/mel_constants.rs\n")
    file.write(" *  wake-word-detector\n")
    file.write(" *\n")
    file.write(" *  Created by Joel Lopes Da Silva on 2/14/26.\n")
    file.write(" *  Copyright © 2026 Joel Lopes Da Silva. All rights reserved.\n")
    file.write(" *\n")
    file.write(" *  Generated by spoken-word-detection-model/generate_rust_constants.py.\n")
    file.write(" *  Do not edit manually.\n")
    file.write(" *\n")
    file.write(" */\n")
    file.write("\n")

    file.write("/// Periodic Hann window (512 coefficients).\n")
    file.write("pub const HANN_WINDOW: [f32; 512] = [\n")
    for value in hann:
        file.write(f"    {value:.8f},\n")
    file.write("];\n")
    file.write("\n")

    file.write(f"/// Sparse mel filterbank: first non-zero FFT bin for each of the {number_of_mel_bins} mel bins.\n")
    file.write(f"pub const MEL_BIN_STARTS: [usize; {number_of_mel_bins}] = [\n")
    for value in mel_bin_starts:
        file.write(f"    {value},\n")
    file.write("];\n")
    file.write("\n")

    file.write(f"/// Sparse mel filterbank: number of non-zero weights for each mel bin.\n")
    file.write(f"pub const MEL_BIN_LENGTHS: [usize; {number_of_mel_bins}] = [\n")
    for value in mel_bin_lengths:
        file.write(f"    {value},\n")
    file.write("];\n")
    file.write("\n")

    file.write(f"/// Sparse mel filterbank: offset into MEL_WEIGHTS for each mel bin.\n")
    file.write(f"pub const MEL_BIN_OFFSETS: [usize; {number_of_mel_bins}] = [\n")
    for value in mel_bin_offsets:
        file.write(f"    {value},\n")
    file.write("];\n")
    file.write("\n")

    file.write(f"/// Sparse mel filterbank: packed non-zero weights ({total_weights} values).\n")
    file.write(f"pub const MEL_WEIGHTS: [f32; {total_weights}] = [\n")
    for value in all_weights:
        file.write(f"    {value:.8f},\n")
    file.write("];\n")
    file.write("\n")