#
#  generate_rust_constants.py
#  wake-word-detector/spoken-word-detection-model
#
#  Created by Joel Lopes Da Silva on 2/14/26.
#  Copyright © 2026 Joel Lopes Da Silva. All rights reserved.
#

import tensorflow as tf

hann = tf.signal.hann_window(512, periodic=True).numpy()

# The parameters must match those in `data_loader.py` exactly.
mel_matrix = tf.signal.linear_to_mel_weight_matrix(
    num_mel_bins=40,
    num_spectrogram_bins=257,    # FFT_length / 2 + 1
    sample_rate=16000,
    lower_edge_hertz=80.0,
    upper_edge_hertz=7600.0,
).numpy()

with open("../src/mel_constants.rs", "w") as file:
    file.write("/*\n")
    file.write(" *  mel_constants.rs\n")
    file.write(" *  wake-word-detector\n")
    file.write(" *\n")
    file.write(" *  Created by Joel Lopes Da Silva on 2/14/26.\n")
    file.write(" *  Copyright © 2026 Joel Lopes Da Silva. All rights reserved.\n")
    file.write(" *\n")
    file.write(" *  Generated by spoken-word-detection-model/generate_rust_constants.py.\n")
    file.write(" *  Do not edit manually.\n")
    file.write(" *\n")
    file.write(" */\n")
    file.write("\n")
    file.write("/// Periodic Hann window (512 coefficients).\n")
    file.write("pub const HANN_WINDOW: [f32; 512] = [\n")
    for value in hann:
        file.write(f"    {value:.8f},\n")
    file.write("];\n")
    file.write("\n")
    file.write("/// Mel filterbank (257 rows × 40 columns, row-major).\n")
    file.write("pub const MEL_FILTERBANK: [f32; 10280] = [\n")
    file.write("\n")
    number_of_frequency_bins, number_of_mel_bins = mel_matrix.shape
    for frequency_bin_index in range(number_of_frequency_bins):
        file.write(f"    // Frequency bin {frequency_bin_index}\n")
        for mel_bin_index in range(number_of_mel_bins):
            value = mel_matrix[frequency_bin_index, mel_bin_index]
            file.write(f"    {value:.8f},\n")
        file.write("\n")
    file.write("];\n")