#
#  .cargo/config.toml
#  wake-word-detector
#
#  Created by Joel Lopes Da Silva on 2/14/26.
#  Copyright © 2026 Joel Lopes Da Silva. All rights reserved.
#

#---------------------------------------------------------------
# Build options
#---------------------------------------------------------------

[build]
# Default target set to the match the Cortex-M33 in the RP2350
# for a Raspberry Pi Pico 2 in ARM mode.
target = "thumbv8m.main-none-eabihf"


#---------------------------------------------------------------
# Configuration for Raspberry Pi Pico 2 (RP2350) in ARM mode
#---------------------------------------------------------------

# This is the hard-float ABI for ARM mode with the Cortex-M33
# in the RP2350.
#
# The FPU is enabled by default, and float function arguments use FPU
# registers.
[target.thumbv8m.main-none-eabihf]

# Pass some extra options to `rustc`, some of which get passed on
# to the linker.
#
# * linker argument `--nmagic` turns off page alignment of sections
#   (which saves flash space).
# * linker argument `-Tlink.x` tells the linker to use `link.x`
#   as a linker script.
#   This is usually provided by the `cortex-m-rt` crate, and by default
#   the version in that crate will include a file called `memory.x`
#   which describes the particular memory layout for your specific chip.
# * linker argument `-Tdefmt.x` also tells the linker to use `defmt.x`
#   as a secondary linker script.
#   This is required to make `defmt_rtt` work.
rustflags = [
    "-C", "link-arg=--nmagic",
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=-Tdefmt.x",
    "-C", "target-cpu=cortex-m33",
]

# Use `probe-rs` for running the executable on the microcontroller.
runner = "probe-rs run --chip rp235x --protocol swd"

# Alternative to use `picotool` for loading.
#
# Load an elf, skipping unchanged flash sectors, verify it, and execute it.
#runner = "${PICOTOOL_PATH} load -u -v -x -t elf"


#---------------------------------------------------------------
# Environment
#---------------------------------------------------------------

[env]
DEFMT_LOG = "debug"
